// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovifxnzihqkmxigerolm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92aWZ4bnppaHFrbXhpZ2Vyb2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTIxNzQsImV4cCI6MjA2MTMyODE3NH0.KExRi5P8euD8cb34oRWyxT6WXOoUU4JfMfhDYrO-oi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);